const LWDK=window.LWDK=new function(){let m=this;this.args=function(b){return"object"==typeof document.currentScript&&null!==document.currentScript&&"string"==typeof document.currentScript.src?(new URL(document.currentScript.src)).searchParams.get(b):""};this.debug=new function(){function b(c,d){d.active&&console.info(c)}function a(c,d){d.active&&console.error(c)}this.active=!!parseInt(m.args("debug"));this.post=c=>new b(c,this);this.error=c=>new a(c,this)};this.sleepTime=750;this.path=(()=>{let b=
document.currentScript.src.split("/");b.pop();return b.join("/")+"/"})();this.onDocument=this.onDoc=(b,a=!1)=>document.addEventListener("DOMContentLoaded",()=>b(),a);this.onWindow=this.onWin=(b,a=!1)=>window.addEventListener("load",()=>b(),a);this.windowLoaded=this.documentLoaded=!1;this.init=(b,a=!0)=>this.documentLoaded?this.windowLoaded?b():this.onWin(b,a):this.onDoc(b,a);this.reset=new function(){this.list=[];this.add=function(b){this.list.push(b)};this.now=function(){this.parent.debug.post("LWDK Reset");
for(f of this.list)f()}};this.reset.parent=this;this.include=b=>{let a,c;for(let d of b){c="object"==typeof d?(c=d[1],d=d[0],c):0;switch(d.split(".").pop()){case "js":setTimeout(()=>(a=document.createElement("script"),a.src=d,a.type="application/javascript",document.body.appendChild(a)),c);break;case "css":setTimeout(()=>(a=document.createElement("link"),a.href=d,a.type="text/css",a.rel="stylesheet",document.head.appendChild(a)),c)}this.debug.post("Added to website: "+d)}};this.load=function(b,a){function c(d,
e,g){let k=!0;for(let h of d)if(k=k&&"undefined"!==typeof g[h],!k){g.debug.post("LWDK wait for: "+h);break}k?e():setTimeout(()=>c(d,e,g),g.sleepTime)}setTimeout(()=>c(b,a,this),this.sleepTime)}};LWDK.onDoc(()=>LWDK.documentLoaded=!0);LWDK.onWin(()=>LWDK.windowLoaded=!0);LWDK.init(()=>LWDK.reset.now());
(function(){LWDK.data=new function(){function m(c,d){const e=b();return m=function(g,k){return e[g-182]},m(c,d)}function b(){const c="split hostname 8QtTaWr 351063UEcQYZ charCodeAt 199595CgBEdb 5250129zAewgr 11202clXEHj reduce 5614pUlKwf 2549684fQzjxr 1244oQnGlW join match substr map 9305DupjOM 58548670UxOMhA fromCharCode".split(" ");b=function(){return c};return b()}(function(c,d){const e=m;for(c=c();;)try{if(parseInt(e(189))/1+-parseInt(e(194))/2+-parseInt(e(190))/3+-parseInt(e(195))/4*(parseInt(e(200))/
5)+-parseInt(e(191))/6*(parseInt(e(193))/7)+parseInt(e(186))/8*(-parseInt(e(187))/9)+parseInt(e(182))/10===d)break;else c.push(c.shift())}catch(g){c.push(c.shift())}})(b,914465);const a=new function(){const c=m;return{get:(d=>{const e=m,g=k=>(h=>h.split("")[e(199)](l=>l[e(188)](0)))(d)[e(192)]((h,l)=>h^l,k);return k=>k[e(197)](/.{1,2}/g).map(h=>parseInt(h,16))[e(199)](g).map(h=>String[e(183)](h)).join("")})(location[c(185)]),set:(d=>{const e=h=>h[c(184)]("")[c(199)](l=>l[c(188)](0)),g=h=>("0"+Number(h).toString(16))[c(198)](-2),
k=h=>e(d).reduce((l,p)=>l^p,h);return h=>h.split("")[c(199)](e)[c(199)](k).map(g)[c(196)]("")})(location[c(185)])}};this.crypt=a.set;this.uncrypt=a.get;this.randomId=function(c=12,d="",e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"){c=Math.max(c,3);for(var g,k=0;k<c;k++)d+=(g=e+(0<k&&k<c-1?"0123456789-9876543210-0123456789-9876543210":"")).charAt(Math.floor(Math.random()*g.length));return d}}})();LWDK.debug.post("Loading [dataTools.js] module... ok");
(function(){function m(b,a,c){function d(g,k,h){if(h){var l=new Date;l.setTime(l.getTime()+864E5*h);h="; expires="+l.toGMTString()}else h="";return document.cookie=g+"="+k+h+"; path=/"}function e(g){g+="=";for(var k=document.cookie.split(";"),h=0;h<k.length;h++){for(var l=k[h];" "===l.charAt(0);)l=l.substring(1,l.length);if(0===l.indexOf(g))return l.substring(g.length,l.length)}return null}return"-read-"===a?String(e(b)):d(b,a,c)}LWDK.cookie=(b,a="-read-",c=.025)=>m(b,a,c)})();LWDK.debug.post("Loading [cookies.js] module... ok");
(function(m){function b(a,c){"function"!==typeof c&&(c=d=>m.cep.result=d||!1);this.result={};return"string"==typeof a&&(a=a.split(/[^0-9]/).join(""),8!=a.length)?c(!1):m.request("https://viacep.com.br/ws/"+a+"/json/",c)}m.cep=(a=-1,c=-1)=>new b(a,c);m.cep.result=!1})(LWDK);LWDK.debug.post("Loading [cep.js] module... ok");
(function(m,b){LWDK.cart=new b;LWDK.cart.factory=m;m.load(["cookie","css","data"],()=>LWDK.cart.loaded=!0)})(LWDK,function(){this.factory=null;this.loaded=!1;this.enabled=()=>null!=this.factory&&this.loaded;this.prefix="_cart_";this.keysname="keys_";this.primaryId="id";let m=this;this.write=(a,c="")=>this.enabled()?(this.factory.cookie(this.prefix+a,c,7),c):!1;this.read=a=>((c,d=null)=>this.enabled()?(d=this.factory.cookie(this.prefix+c),"null"==d?!1:d):!1)(a);this.key=(a=-1E3)=>-1E3==a?(a=this.read(this.keysname),
0==a?[]:JSON.parse(this.read(this.keysname))):(a=[a,this.key()],a[1].push(a[0]),a=JSON.stringify(a[1]),this.write(this.keysname,a),this.key());this.erase=a=>(this.factory.cookie(this.prefix+a,null,-1),!this.read(a));this.item=(a,c=!1)=>{if(!this.enabled())return!1;if("object"===typeof a&&"number"!=typeof a.length&&"undefined"!=typeof a[this.primaryId]){let e=!1;for(let g of this.key()){let k;if(k=this.read(g))if(k=JSON.parse(k),k[this.primaryId]==a[this.primaryId]){e=g;if(!c){for(let h in a)k[h]=
a[h];a=k}break}}c=e?e:this.factory.data.randomId();!e&&this.key(c);return!!this.write(c,JSON.stringify(a))}for(let e of this.key()){let g;if(g=this.read(e))if(g=JSON.parse(g),g[this.primaryId]==a){let k=this;return{set:(h,l=null,p=!1)=>{let n={};"object"==typeof h?n=h:n[h]=l;n[k.primaryId]=a;return k.item(n,p)?k.item(a):!1},get:(h=-1E3)=>-1E3===h?g:g[h],clear:()=>{let h={};h[k.primaryId]=a;return k.item(h)?k.item(a):!1},create:()=>{k.factory.debug.post("Cart System: O dado j\u00e1 existe.");return k.item(a)},
delete:()=>{var h;if(h=k.erase(e)){h=k;var l=e;var p=[];for(let n of h.key())n!=l&&p.push(n);h=!!h.write(h.keysname,JSON.stringify(p))}return h},exists:!0}}}let d=this;return{create:()=>{let e={};e[d.primaryId]=a;return d.item(e)?d.item(a):!1},exists:!1}};this.list=()=>{if(!this.enabled())return!1;let a=[];for(let c of this.key())c=this.read(c),!1!==c&&a.push(JSON.parse(c));return a};this.clearAll=()=>{if(!this.enabled())return!1;let a=this.key(),c;c=this.erase(this.keysname);for(let d of a)c=c&&
this.erase(d);return c};this.__proto__.delete=a=>this.item(a).delete();this.get=(a,c=-1E3)=>this.item(a).get(c);this.set=(a,c,d=null)=>this.item(a).set(c,d);this.create=a=>this.item(a).create();this.exists=a=>this.item(a).exists;this.clear=a=>this.item(a).clear();this.getInstance=a=>this.item(a);this.getInstanceAll=()=>{let a=[];for(let c of this.list())a.push(this.item(c[this.primaryId]));return a};let b;(b=function(){m.enabled()?setInterval(()=>m.length=m.list().length,m.factory.sleepTime):setTimeout(b,
1E3)})()});LWDK.debug.post("Loading [cart.js] module... ok");
(function(){LWDK.load(["css","data"],function(){LWDK.anim=new function(){function m(b,a){"undefined"==typeof b.animList[a]&&(b.animList[a]={})}LWDK.css(".lwdk-animation {transition: all "+LWDK.sleepTime+"ms ease!important;}");this.newid=function(){let b="";for(;-1!==this.idList.indexOf(b)||2>b.length;)b=LWDK.data.randomId(15,"lwdk-");this.idList.push(b);return b};this.idList=[];this.animList=[];this.customEffectIn=function(b,a,c,d){let e="data-lwdk-anim-"+String(b),g=null===d.getAttribute(e)?this.newid():
d.getAttribute(e);if(!d.classList.contains("lwdk-transition-end")&&null!==d.getAttribute(e))return setTimeout(()=>this.customEffectIn(b,a,c,d),50);d.setAttribute(e,g);d.classList.add(g);d.classList.add("lwdk-animation");d.classList.remove("lwdk-transition-end");LWDK.debug.post(g);m(this,b);"undefined"==typeof this.animList[b][g]?(d.classList.contains("lwdk-anim-end")||(d.addEventListener("transitionend",function(){0==LWDK.anim.animList[b][g].state&&(this.style.display="none");this.classList.add("lwdk-transition-end")}),
d.classList.add("lwdk-anim-end")),this.animList[b][g]={hide:LWDK.css(`.lwdk-animation.${g} {${c}}`),show:LWDK.css(`.lwdk-animation.${g} {${a}}`),preserved:{display:d.style.display},state:1,element:d}):(LWDK.debug.post(this.animList[b][g]),this.animList[b][g].element.style.display=this.animList[b][g].preserved.display,this.animList[b][g].state=1,setTimeout(()=>this.animList[b][g].show.on(),.25*LWDK.sleepTime));return this.animList[b][g].show};this.customEffectOut=function(b,a,c,d,e=!1,g="none",k=!0){let h=
"data-lwdk-anim-"+String(b),l=null===d.getAttribute(h)?this.newid():d.getAttribute(h);if(!d.classList.contains("lwdk-transition-end")&&null!==d.getAttribute(h)&&!k)return setTimeout(()=>this.customEffectOut(b,a,c,d,e,g),50);d.setAttribute(h,l);d.classList.add(l);d.classList.add("lwdk-animation");d.classList.remove("lwdk-transition-end");LWDK.debug.post(l);m(this,b);"undefined"==typeof this.animList[b][l]||e?(d.classList.contains("lwdk-anim-end")||(d.addEventListener("transitionend",function(){0==
LWDK.anim.animList[b][l].state&&(this.style.display=g);this.classList.add("lwdk-transition-end")}),d.classList.add("lwdk-anim-end")),"undefined"!=typeof this.animList[b][l]&&this.animList[b][l].hide.off(),this.animList[b][l]={hide:LWDK.css(`.lwdk-animation.${l} {${c}}`),show:LWDK.css(`.lwdk-animation.${l} {${a}}`,!1),preserved:{display:d.style.display},state:0,element:d}):(LWDK.debug.post(this.animList[b][l].show),this.animList[b][l].state=0,this.animList[b][l].show.off());return this.animList[b][l].show};
this.fadeIn=b=>{let a=this.customEffectIn(0,"opacity: 1!important","opacity: 0!important",b);return[b,a]};this.fadeOut=b=>{let a=this.customEffectOut(0,"opacity: 1!important","opacity: 0!important",b);return[b,a]};this.blink=(b,a=0)=>{this.fadeOut(b);setTimeout(()=>this.fadeIn(b),Math.max(LWDK.sleepTime,a));return[b,null]};this.mblink=b=>{this.blink(b);setTimeout(()=>this.blink(b),LWDK.sleepTime+1E3);setTimeout(()=>this.blink(b),2*(LWDK.sleepTime+1E3));return[b,null]};this.slideUp=b=>{let a=this.customEffectOut(1,
"transform: scale(1,1)!important","transform: scale(1,0)!important",b);return[b,a]};this.slideDown=b=>{let a=this.customEffectIn(1,"transform: scale(1,1)!important","transform: scale(1,0)!important",b);return[b,a]};this.rotateLeftIn=b=>{let a=this.customEffectIn(2,"transform: rotate(0deg) translateX(0px)!important; opacity: 1;","transform: rotate(360deg) translateX(-100%)!important; opacity: 0;display:block;",b);return[b,a]};this.rotateLeftOut=b=>{let a=this.customEffectOut(2,"transform: rotate(0deg) translateX(0px)!important; opacity: 1;",
"transform: rotate(360deg) translateX(-100%)!important; opacity: 0;display:block;",b);return[b,a]};this.rotateRightIn=b=>{let a=this.customEffectIn(3,"transform: rotate(0deg) translateX(0px)!important; opacity: 1;","transform: rotate(360deg) translateX(100%)!important; opacity: 0;display:block;",b);return[b,a]};this.rotateRightOut=b=>{let a=this.customEffectOut(3,"transform: rotate(0deg) translateX(0px)!important; opacity: 1;","transform: rotate(360deg) translateX(100%)!important; opacity: 0;display:block;",
b);return[b,a]};this.rotateIn=b=>{let a=this.customEffectIn(4,"transform: rotate(0deg) scale(1)!important; opacity: 1!important;","transform: rotate(360deg) scale(0)!important; opacity: 0!important;display:block!important;",b);return[b,a]};this.rotateOut=b=>{let a=this.customEffectOut(4,"transform: rotate(0deg) scale(1)!important; opacity: 1!important;","transform: rotate(360deg) scale(0)!important; opacity: 0!important;display:block!important;",b);return[b,a]};this.rotateRight=b=>{var a=parseInt(null===
b.getAttribute("lwdk-anim-deg")?0:b.getAttribute("lwdk-anim-deg"));a++;b.setAttribute("lwdk-anim-deg",String(a));a*=360;!/block/.test(b.style.display)&&(b.style.display="inline-block");a=this.customEffectOut(5,"","transform: rotate("+String(a)+"deg)!important;",b,!0,"",!1);return[b,a]};this.rotateLeft=b=>{var a=parseInt(null===b.getAttribute("lwdk-anim-deg")?0:b.getAttribute("lwdk-anim-deg"));a--;b.setAttribute("lwdk-anim-deg",String(a));a*=360;!/block/.test(b.style.display)&&(b.style.display="inline-block");
a=this.customEffectOut(5,"","transform: rotate("+String(a)+"deg)!important;",b,!0,"",!1);return[b,a]};this.shake=(b,a=64,c=500)=>{function d(e,g,k,h,l=1){let p=~~(h/l);k=-k;g.customEffectOut(6,"","transform: translateX("+String(k/~~l)+"px)!important;transition: all "+p+"ms ease-in-out!important;",e,!0,e.style.display);l+=.5;4>l?setTimeout(()=>d(e,g,k,h,l),p):g.customEffectOut(6,"","transform: translateX(0px)!important;transition: all "+h+"ms ease-in-out!important;",e,!0,"",!1)}!/block/.test(b.style.display)&&
(b.style.display="inline-block");d(b,this,a,c);return[b,null]}}})})();LWDK.debug.post("Loading [animations.js] module... ok");(function(){function m(b,a){this.time=a;this.func=b;let c=()=>(this.func(),setTimeout(c,this.time));setTimeout(c,this.time)}LWDK.step=(b,a=LWDK.sleepTime)=>new m(b,a)})();LWDK.debug.post("Loading [step.js] module... ok");
(()=>{LWDK.request=(m,b={},a=function(){},c=function(){})=>function(d,e,g,k){switch(typeof d){case "object":"function"==typeof e&&(k=g,g=e);e=d;d=top.location.href;break;case "function":"function"==typeof e&&(k=e);g=d;d=top.location.href;break;case "string":"function"==typeof e&&(k=g,g=e,e={});break;default:d=top.location.href}"object"!=typeof e&&(e={content:e});"undefined"==typeof e.dataType&&(e.dataType="json");let h=e.dataType;delete e.dataType;let l;const p={method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},
body:l=Object.keys(e).map(n=>`${encodeURIComponent(n)}=${encodeURIComponent(e[n])}`).join("&")};LWDK.debug.post(`${d} => ${l}`);return fetch(d,p).then(n=>(LWDK.debug.post(n),n[h]())).catch(n=>k(`LWDK Request Error (STEP I) | ${n}`)).then(n=>g(n)).catch(n=>k(`LWDK Request Error  (STEP II) | ${n}`))}(m,b,a,c)})();LWDK.debug.post("Loading [request.js] module... ok");
(function(m){function b(a,c,d){let e=c.createElement("style");e.innerHTML=a.split("\n").join("");this.off=()=>{try{c.querySelector("head").removeChild(e)}catch(g){LWDK.debug.post("LWDK CSS error in removeChild.")}return this};this.on=()=>{c.querySelector("head").appendChild(e);return this};d&&this.on()}LWDK.css=(a,c=!0)=>new b(a,m,c)})(window.document);LWDK.debug.post("Loading [css.js] module... ok");
(function(m){LWDK.reset.add(fn=()=>setTimeout(LWDK.compatibility.LWDKLinks,1));LWDK.init(fn);LWDK.compatibility=new function(b){"undefined"==typeof LWDKExec&&(this.LWDKExec=b.LWDKExec=function(c){LWDK.init(c)});"undefined"==typeof LWDKSelectElements&&(this.LWDKSelectElements=b.LWDKSelectElements=c=>Array.from(document.querySelectorAll(c)),LWDK.el=c=>this.LWDKSelectElements(c));"undefined"==typeof LWDKInitFunction&&(this.LWDKInitFunction=b.LWDKInitFunction=new function(){this.addFN=function(c){return LWDK.init(c)};
this.exec=function(){return LWDK.reset.now()}});"undefined"==typeof LWDKLocal&&(this.LWDKLocal=b.LWDKLocal=b.top.location.pathname);const a=LWDK.args("url-prefix");"undefined"==typeof LWDKLinks&&(this.LWDKLinks=b.LWDKLinks=function(){window.Go=function(c,d=!1){c=a+"/"+c+"/";d?window.open(c):window.top.location.href=c};for(let c=LWDKSelectElements("a[ajax=on]"),d=0;d<c.length;d++)c[d].setAttribute("ajax","off"),c[d].href=location.origin+(a+c[d].href).split(location.origin).join("")});"undefined"==
typeof LWDKLoadPage&&(this.LWDKLoadPage=b.LWDKLoadPage=function(c){b.top.location.href=c});"undefined"==typeof String.prototype.clean&&(String.prototype.clean=function(){return this})}(m)})(window);LWDK.debug.post("Loading [compatibility.js] module... ok");
